# Generated by Django 4.2.17 on 2025-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название книги"),
        ),
    ]
