# Generated by Django 4.2.17 on 2025-01-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0002_alter_book_author_alter_book_author_email_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Укажите ваше имя")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, verbose_name="Укажите номер вашего телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Укажите свою почту(необязательно)",
                    ),
                ),
                ("address", models.TextField(verbose_name="Укажите адрес доставки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="library.book"
                    ),
                ),
            ],
        ),
    ]
