# Generated by Django 4.2.17 on 2025-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Укажите ваше имя"),
        ),
    ]
